VERZIJA=CDX
MODUL=fmk_trm

# SRCDOSROOT=$(BASEDOS)\\fmk\\fmk_co~1\\bterm\\

SRCDOSROOT=$(BASEDOS)\\fmk\\fmk_c\\bterm\\


PRGS=db.prg main.prg ut.prg
CS=
ASMS=

include ../../fmk_lib/Makefile_clipper

