ROOT = ../../harbour/harbour/

HB_INC_COMPILE += -I$(TOP)../../fmk_lib/include

PRG_SOURCES= \
   rb_traka.prg pf_a4.prg pf_a4_2.prg pf_traka.prg pf_db.prg rn_ut.prg otpr_mp.prg nar.prg rnal.prg

LIBNAME=fmk_racuni

include $(TOP)$(ROOT)config/lib.cf

HB_FLAGS = -n -b -ufmk_std.ch -kM -gc0 -I$(TOP) -I$(HB_INC_COMPILE)
