VERZIJA=CDX
MODUL=ld_1dok

SRCDOSROOT=c:\\dev\\fmk\\ld\\dok\\1g\\

PRGS=mnu_obr.prg mnu_bris.prg mnu_rek.prg unos.prg brisi.prg rekalk.prg zak_obr.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
