VERZIJA=CDX
MODUL=fmk_rn

SRCDOSROOT=$(BASEDOS)\\fmk\\fmk_co~1\\rn\\


PRGS=rb_traka.prg pf_a4.prg pf_a4_2.prg pf_traka.prg pf_db.prg rn_ut.prg otpr_mp.prg nar.prg rnal.prg
CS=
ASMS=

include ../../fmk_lib/Makefile_clipper
