VERZIJA=CDX
MODUL=fmk_rn

SRCDOSROOT=c:\\dev\\fmk\\\AF\\cl-AF\\rn\\


PRGS=rb_traka.prg pf_a4.prg pf_a4_2.prg pf_traka.prg pf_db.prg rn_ut.prg otpr_mp.prg nar.prg rnal.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
