ROOT = ../../harbour/harbour/

HB_INC_COMPILE += -I$(TOP)../../fmk_lib/include

PRG_SOURCES= \
   adm_db.prg gvars.prg id_j.prg koncij.prg \
   sifk.prg sifre.prg trfp.prg rlabele.prg \
   barkod.prg \
   ut.prg db_integracija.prg int_util.prg \
   strings.prg label.prg label_1.prg label_2.prg \

LIBNAME=fmk_roba

include $(TOP)$(ROOT)config/lib.cf

HB_FLAGS = -n -b -ufmk_std.ch -kM -gc0 -I$(TOP) -I$(HB_INC_COMPILE)


