ROOT = ../../harbour/harbour/

HB_INC_COMPILE += -I$(TOP)../fmk_lib/include

PRG_SOURCES= \
	    db_rule.prg  m_rules.prg  rules.prg

LIBNAME=fmk_rules

include $(TOP)$(ROOT)config/lib.cf

HB_FLAGS = -n -b -ufmk_std.ch -kM -gc0 -I$(TOP) -I$(HB_INC_COMPILE)


