VERZIJA=CDX
MODUL=fmk_ugov

SRCDOSROOT=$(BASEDOS)\\fmk\\fmk_co~1\\ugov\\

PRGS=ugov.prg genug.prg genug2.prg dest.prg m_ugov.prg rugov.prg db_ugov.prg param.prg ut.prg g_fin.prg dest_2.prg
CS=
ASMS=

include ../../fmk_lib/Makefile_clipper
