VERZIJA=CDX
MODUL=fmk_mes


SRCDOSROOT=c:\\dev\\fmk\\AF\\cl-AF\\message\\

PRGS=db.prg main.prg app_msg.prg mnu_msg.prg rpt_msg.prg

CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
