VERZIJA=CDX
MODUL=ld_1rpt

SRCDOSROOT=c:\\dev\\fmk\\ld\\rpt\\1g\\

PRGS=mnu_izvj.prg rpt_rek.prg izvj.prg izvj2.prg rpt_spec.prg rpt_kart.prg rpt_plsp.prg rpt_ppl.prg rpt_prim.prg rpt_rek.prg rpt_rnet.prg rpt_pprn.prg rpt_ahon.prg rpt_ut.prg rpt_to.prg rpt_por.prg rpt_dop.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
