VERZIJA=CDX
MODUL=fmk_roba

SRCDOSROOT=$(BASEDOS)\\fmk\\fmk_co~1\\roba\\

PRGS=adm_db.prg db.prg gvars.prg id_j.prg koncij.prg roba.prg rpt_cjen.prg rpt_sast.prg sast.prg sifk.prg sifre.prg tarifa.prg trfp.prg rlabele.prg ut.prg int_db.prg int_util.prg strings.prg label.prg label_1.prg label_2.prg
CS=
ASMS=

include ../../fmk_lib/Makefile_clipper
