VERZIJA=CDX
MODUL=fmk_roba

SRCDOSROOT=c:\\dev\\fmk\\\AF\\cl-AF\\roba\\

PRGS=adm_db.prg db.prg gvars.prg id_j.prg koncij.prg roba.prg rpt_cjen.prg rpt_sast.prg sast.prg sifk.prg sifre.prg tarifa.prg trfp.prg barkod.prg rlabele.prg ut.prg int_db.prg int_util.prg gr_db.prg gr_sif.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
