VERZIJA=CDX
MODUL=fiscal

SRCDOSROOT=$(BASEDOS)\\fmk\\fmk_co~1\\fiscal\\


PRGS=txt_f.prg main.prg tring.prg flink.prg fprint.prg util.prg hcp.prg tremol.prg f_rpt.prg
CS=
ASMS=

include ../../fmk_lib/Makefile_clipper

