#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  5
#define DVAR1  "01"
#define DVAR2  _s01
#define DVAR3  _i01
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  6
#define DVAR1  "02"
#define DVAR2  _s02
#define DVAR3  _i02
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  7
#define DVAR1  "03"
#define DVAR2  _s03
#define DVAR3  _i03
#include "c:\re\ld\e2.ch"


#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  8
#define DVAR1  "04"
#define DVAR2  _s04
#define DVAR3  _i04
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  9
#define DVAR1  "05"
#define DVAR2  _s05
#define DVAR3  _i05
#include "c:\re\ld\e2.ch"


#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  10
#define DVAR1  "06"
#define DVAR2  _s06
#define DVAR3  _i06
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  11
#define DVAR1  "07"
#define DVAR2  _s07
#define DVAR3  _i07
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  12
#define DVAR1  "08"
#define DVAR2  _s08
#define DVAR3  _i08
#include "c:\re\ld\e2.ch"


#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  13
#define DVAR1  "09"
#define DVAR2  _s09
#define DVAR3  _i09
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  14
#define DVAR1  "10"
#define DVAR2  _s10
#define DVAR3  _i10
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  15
#define DVAR1  "11"
#define DVAR2  _s11
#define DVAR3  _i11
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  16
#define DVAR1  "12"
#define DVAR2  _s12
#define DVAR3  _i12
#include "c:\re\ld\e2.ch"


#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  17
#define DVAR1  "13"
#define DVAR2  _s13
#define DVAR3  _i13
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  18
#define DVAR1  "14"
#define DVAR2  _s14
#define DVAR3  _i14
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  19
#define DVAR1  "15"
#define DVAR2  _s15
#define DVAR3  _i15
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED  20
#define DVAR1  "16"
#define DVAR2  _s16
#define DVAR3  _i16
#include "c:\re\ld\e2.ch"

read

@ m_x+4,m_y+2  CLEAR TO m_x+20,m_y+69

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   5
#define DVAR1  "17"
#define DVAR2  _s17
#define DVAR3  _i17
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   6
#define DVAR1  "18"
#define DVAR2  _s18
#define DVAR3  _i18
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   7
#define DVAR1  "19"
#define DVAR2  _s19
#define DVAR3  _i19
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   8
#define DVAR1  "20"
#define DVAR2  _s20
#define DVAR3  _i20
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   9
#define DVAR1  "21"
#define DVAR2  _s21
#define DVAR3  _i21
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   10
#define DVAR1  "22"
#define DVAR2  _s22
#define DVAR3  _i22
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   11
#define DVAR1  "23"
#define DVAR2  _s23
#define DVAR3  _i23
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   12
#define DVAR1  "24"
#define DVAR2  _s24
#define DVAR3  _i24
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   13
#define DVAR1  "25"
#define DVAR2  _s25
#define DVAR3  _i25
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   14
#define DVAR1  "26"
#define DVAR2  _s26
#define DVAR3  _i26
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   15
#define DVAR1  "27"
#define DVAR2  _s27
#define DVAR3  _i27
#include "c:\re\ld\e2.ch"


#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   16
#define DVAR1  "28"
#define DVAR2  _s28
#define DVAR3  _i28
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   17
#define DVAR1  "29"
#define DVAR2  _s29
#define DVAR3  _i29
#include "c:\re\ld\e2.ch"

#undef DRED
#undef DVAR1
#undef DVAR2
#undef DVAR3
#define DRED   18
#define DVAR1  "30"
#define DVAR2  _s30
#define DVAR3  _i30
#include "c:\re\ld\e2.ch"

read


