VERZIJA=CDX
MODUL=fmk_svi

SRCDOSROOT=c:\\dev\\fmk\\AF\\cl-AF\\svi\\

PRGS=adm_db.prg db.prg fmk_ut.prg gvars.prg konto.prg ops.prg partn.prg rj.prg sifre.prg ut.prg valute.prg vn_vd.prg specif.prg rpt_all.prg rnal.prg dok_src.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper


fmk_ut.obj : $(SC_BUILD_HOME_DIR)/sclib/sc.ch $(SC_BUILD_HOME_DIR)/sclib/std_cdx.ch ../fmk.ch
