VERZIJA=CDX
MODUL=fmk_ugov

SRCDOSROOT=c:\\dev\\fmk\\AF\\cl-AF\\ugov\\

PRGS=ugov.prg genug.prg genug2.prg dest.prg m_ugov.prg rugov.prg db_ugov.prg param.prg ut.prg g_fin.prg dest_2.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
