*SUBAN.DBF
C IDPARTNER C 6 0  IDPARTNER C 8 0

*PSUBAN.DBF
C IDPARTNER C 6 0  IDPARTNER C 8 0

*PRIPR.DBf
C IDPARTNER C 6 0  IDPARTNER C 8 0

*IOS.DBF
C IDPARTNER C 6 0  IDPARTNER C 8 0

*PARTN.DBF
C ID C 6 0 ID C 8 0

*ULIMIT.DBF
C IDPARTNER C 6 0  IDPARTNER C 8 0

