ROOT = ../../harbour/harbour/

HB_INC_COMPILE += -I$(TOP)../../fmk_lib/include

PRG_SOURCES= \
          adm_db.prg \
          db.prg dok_src.prg \
          fmk_ut.prg \
          gvars.prg konto.prg \
          ops.prg   partn.prg \
          relation.prg \
          rj.prg \
          rnal.prg \
          rpt_all.prg \
          sifre.prg \
          specif.prg \
          ut.prg \
          valute.prg \
          vn_vd.prg


LIBNAME=fmk_svi

include $(TOP)$(ROOT)config/lib.cf

HB_FLAGS = -n -b -ufmk_std.ch -kM -gc0 -I$(TOP) -I$(HB_INC_COMPILE)


